// SPDX-License-Identifier: Apache-2.0

package javaactions

import (
	"fmt"
	"strings"
)

// GenerateJavaScriptSource renders the .js stub Studio Pro writes for a
// JavaScript action: the generated-file banner, an EXTRA CODE section, a JSDoc
// block, and an exported async function wrapping the user code between
// BEGIN/END USER CODE markers. It is pure (depends only on the action's shape),
// so both engines share it for byte-identical output. userCode is placed inside
// the USER CODE markers; when empty a not-implemented stub is emitted.
func GenerateJavaScriptSource(actionName string, userCode string, params []*JavaActionParameter, returnType CodeActionReturnType) string {
	var sb strings.Builder

	sb.WriteString("// This file was generated by Mendix Studio Pro.\n")
	sb.WriteString("//\n")
	sb.WriteString("// WARNING: Only the following code will be retained when actions are regenerated:\n")
	sb.WriteString("// - the code between BEGIN USER CODE and END USER CODE\n")
	sb.WriteString("// - the code between BEGIN EXTRA CODE and END EXTRA CODE\n")
	sb.WriteString("// Other code you write will be lost the next time you deploy the project.\n")
	sb.WriteString("// Special characters, e.g., é, ö, à, etc. are supported in comments.\n\n")

	sb.WriteString("// BEGIN EXTRA CODE\n")
	sb.WriteString("// END EXTRA CODE\n\n")

	// JSDoc: one @param per parameter, then the @returns.
	sb.WriteString("/**\n")
	for _, p := range params {
		sb.WriteString(fmt.Sprintf(" * @param {%s} %s\n", jsDocType(p.ParameterType), p.Name))
	}
	sb.WriteString(fmt.Sprintf(" * @returns {%s}\n", jsDocReturnType(returnType)))
	sb.WriteString(" */\n")

	// Exported async function with the action's parameters.
	names := make([]string, 0, len(params))
	for _, p := range params {
		names = append(names, p.Name)
	}
	sb.WriteString(fmt.Sprintf("export async function %s(%s) {\n", actionName, strings.Join(names, ", ")))
	sb.WriteString("\t// BEGIN USER CODE\n")
	if strings.TrimSpace(userCode) == "" {
		sb.WriteString("\tthrow new Error(\"JavaScript action '" + actionName + "' was not implemented\");\n")
	} else {
		for _, line := range strings.Split(strings.TrimRight(userCode, "\n"), "\n") {
			sb.WriteString("\t" + line + "\n")
		}
	}
	sb.WriteString("\t// END USER CODE\n")
	sb.WriteString("}\n")

	return sb.String()
}

// jsDocType maps a parameter type to a JSDoc type annotation (best-effort).
func jsDocType(t CodeActionParameterType) string {
	switch typeNameOf(t) {
	case "BooleanType":
		return "boolean"
	case "IntegerType", "LongType", "DecimalType":
		return "number"
	case "StringType", "StringTemplateParameterType":
		return "string"
	case "DateTimeType":
		return "Date"
	default:
		return "*"
	}
}

// jsDocReturnType maps a return type to a JSDoc `Promise.<...>` annotation.
func jsDocReturnType(t CodeActionReturnType) string {
	if t == nil {
		return "Promise.<boolean>"
	}
	switch typeNameOf(t) {
	case "BooleanType":
		return "Promise.<boolean>"
	case "IntegerType", "LongType", "DecimalType":
		return "Promise.<number>"
	case "StringType":
		return "Promise.<string>"
	case "DateTimeType":
		return "Promise.<Date>"
	case "VoidType", "":
		return "Promise.<void>"
	default:
		return "Promise.<MxObject>"
	}
}

// typeNameOf returns the short Go type name of a code-action type element
// (e.g. "*javaactions.StringType" → "StringType"), used for JSDoc mapping.
func typeNameOf(t any) string {
	if t == nil {
		return ""
	}
	s := fmt.Sprintf("%T", t)
	if i := strings.LastIndex(s, "."); i >= 0 {
		s = s[i+1:]
	}
	return s
}
