// SPDX-License-Identifier: Apache-2.0

package javaactions

import (
	"fmt"
	"strings"
)

// GenerateSource renders the .java stub Studio Pro writes for a Java action:
// package, imports, parameter fields + constructor, the executeAction method
// wrapping the user code, toString, and the extra-code section. It is pure
// (depends only on the action's shape), so both the legacy and modelsdk engines
// share it to guarantee byte-identical Java output.
func GenerateSource(moduleName, actionName string, userCode string, params []*JavaActionParameter, returnType CodeActionReturnType, extraImports []string, extraCode string) string {
	moduleNameLower := strings.ToLower(moduleName)

	returnTypeStr := "java.lang.Boolean"
	if returnType != nil {
		returnTypeStr, _ = javaReturnType(returnType)
	}

	var sb strings.Builder

	sb.WriteString("// This file was generated by Mendix Studio Pro.\n")
	sb.WriteString("//\n")
	sb.WriteString("// WARNING: Only the following code will be retained when actions are regenerated:\n")
	sb.WriteString("// - the import list\n")
	sb.WriteString("// - the code between BEGIN USER CODE and END USER CODE\n")
	sb.WriteString("// - the code between BEGIN EXTRA CODE and END EXTRA CODE\n")
	sb.WriteString("// Other code you write will be lost the next time you deploy the project.\n")
	sb.WriteString("// Special characters, e.g., é, ö, à, etc. are supported in comments.\n\n")

	sb.WriteString(fmt.Sprintf("package %s.actions;\n\n", moduleNameLower))

	sb.WriteString("import com.mendix.systemwideinterfaces.core.IContext;\n")
	sb.WriteString("import com.mendix.systemwideinterfaces.core.UserAction;\n")
	for _, imp := range extraImports {
		sb.WriteString(imp)
		sb.WriteString("\n")
	}
	sb.WriteString("\n")

	sb.WriteString(fmt.Sprintf("public class %s extends UserAction<%s>\n", actionName, returnTypeStr))
	sb.WriteString("{\n")

	for _, param := range params {
		javaType := javaParamType(param.ParameterType)
		sb.WriteString(fmt.Sprintf("\tprivate final %s %s;\n", javaType, param.Name))
	}
	sb.WriteString("\n")

	sb.WriteString(fmt.Sprintf("\tpublic %s(\n", actionName))
	sb.WriteString("\t\tIContext context")
	for _, param := range params {
		javaType := javaParamType(param.ParameterType)
		sb.WriteString(fmt.Sprintf(",\n\t\t%s _%s", javaType, strings.ToLower(param.Name[:1])+param.Name[1:]))
	}
	sb.WriteString("\n\t)\n")
	sb.WriteString("\t{\n")
	sb.WriteString("\t\tsuper(context);\n")
	for _, param := range params {
		paramLower := strings.ToLower(param.Name[:1]) + param.Name[1:]
		sb.WriteString(fmt.Sprintf("\t\tthis.%s = _%s;\n", param.Name, paramLower))
	}
	sb.WriteString("\t}\n\n")

	sb.WriteString("\t@java.lang.Override\n")
	sb.WriteString(fmt.Sprintf("\tpublic %s executeAction() throws Exception\n", returnTypeStr))
	sb.WriteString("\t{\n")
	sb.WriteString("\t\t// BEGIN USER CODE\n")
	sb.WriteString("\n")
	for line := range strings.SplitSeq(userCode, "\n") {
		sb.WriteString("\t\t")
		sb.WriteString(line)
		sb.WriteString("\n")
	}
	sb.WriteString("\n")
	sb.WriteString("\t\t// END USER CODE\n")
	sb.WriteString("\t}\n\n")

	sb.WriteString("\t/**\n")
	sb.WriteString("\t * Returns a string representation of this action\n")
	sb.WriteString("\t * @return a string representation of this action\n")
	sb.WriteString("\t */\n")
	sb.WriteString("\t@java.lang.Override\n")
	sb.WriteString("\tpublic java.lang.String toString()\n")
	sb.WriteString("\t{\n")
	sb.WriteString(fmt.Sprintf("\t\treturn \"%s\";\n", actionName))
	sb.WriteString("\t}\n\n")

	sb.WriteString("\t// BEGIN EXTRA CODE\n")
	if extraCode != "" {
		for line := range strings.SplitSeq(extraCode, "\n") {
			sb.WriteString("\t")
			sb.WriteString(line)
			sb.WriteString("\n")
		}
	}
	sb.WriteString("\t// END EXTRA CODE\n")
	sb.WriteString("}\n")

	return sb.String()
}

// javaReturnType maps a return type to its (fully-qualified, simple) Java names.
func javaReturnType(t CodeActionReturnType) (string, string) {
	if t == nil {
		return "java.lang.Boolean", "Boolean"
	}
	switch t.(type) {
	case *VoidType:
		return "java.lang.Void", "Void"
	case *BooleanType:
		return "java.lang.Boolean", "Boolean"
	case *IntegerType:
		return "java.lang.Integer", "Integer"
	case *LongType:
		return "java.lang.Long", "Long"
	case *DecimalType:
		return "java.math.BigDecimal", "BigDecimal"
	case *StringType:
		return "java.lang.String", "String"
	case *DateTimeType:
		return "java.util.Date", "Date"
	case *EntityType:
		return "com.mendix.systemwideinterfaces.core.IMendixObject", "IMendixObject"
	case *ListType:
		return "java.util.List<com.mendix.systemwideinterfaces.core.IMendixObject>", "List"
	default:
		return "java.lang.Object", "Object"
	}
}

// javaParamType maps a parameter type to its fully-qualified Java type.
func javaParamType(t CodeActionParameterType) string {
	if t == nil {
		return "java.lang.Object"
	}
	switch t.(type) {
	case *BooleanType:
		return "java.lang.Boolean"
	case *IntegerType:
		return "java.lang.Integer"
	case *LongType:
		return "java.lang.Long"
	case *DecimalType:
		return "java.math.BigDecimal"
	case *StringType:
		return "java.lang.String"
	case *DateTimeType:
		return "java.util.Date"
	case *EntityType:
		return "com.mendix.systemwideinterfaces.core.IMendixObject"
	case *ListType:
		return "java.util.List<com.mendix.systemwideinterfaces.core.IMendixObject>"
	case *StringTemplateParameterType:
		return "java.lang.String"
	default:
		return "java.lang.Object"
	}
}
